### ISSUE TITLE
Replaced by postcss-responsive-type?

### ISSUE THREAD

**Issue by thebuilder** [ccurtin/postcss-responsive-font#1]
[postcss-responsive-type](https://github.com/seaneking/postcss-responsive-type) is actively maintained, and supports the same options (plus a few more).

**Comment by ccurtin** [comment]
True. postcss-responsive-type does offer more flexibility(line-height & letter-spacing adjustments). postcss-responsive-font was created for quickly adding basic responsive typography in just a single line for easier reading and responsive stacks within a single selector. I think this is a benefit of postcss-responsive-font: allowing multiple responsive fonts in a single selector.
